### ISSUE TITLE
Ubuntu 运行报错

### ISSUE THREAD

**Issue by Cody-Chen** [XIVN1987/QmlSer#1]
Traceback (most recent call last):
  File "QmlSer.py", line 125, in <module>
    qml.rootContext().setContextProperty('Ser', QmlSer(qml.rootContext() ,qml.rootObjects()[0]))
  File "QmlSer.py", line 39, in __init__
    self.ctx.setContextProperty('ports', ['%s (%s)' %(port, desc[:desc.index('(')]) for port, desc, hwid in list_ports.comports()])
  File "QmlSer.py", line 39, in <listcomp>
    self.ctx.setContextProperty('ports', ['%s (%s)' %(port, desc[:desc.index('(')]) for port, desc, hwid in list_ports.comports()])
ValueError: substring not found

**Comment by XIVN1987** [comment]
我只测试过windows，，
看起来Linux下的 list_ports.comports() 返回的 desc 中没有括号，，可以改成下面这样试试
`self.ctx.setContextProperty('ports', ['%s (%s)' %(port, desc) for port, desc, hwid in list_ports.comports()])`

**Comment by Cody-Chen** [comment]
![image](https://user-images.githubusercontent.com/22534155/77505721-e8edad00-6e9e-11ea-85b2-a5260fa81fed.png)
成功了,谢谢
